- name: configure installation
  template:
    src: autosetup.j2
    dest: /autosetup

- name: install image
  command: /root/.oldroot/nfs/install/installimage

- name: reboot into normal mode
  reboot:
    reboot_timeout: 10
  ignore_errors: true
  when: reboot_postinstall

